/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.uvigo.esei.filter;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    public MenuFrame() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setTitle("Main Menu");
        this.setResizable(false);
        //this.setIconImage(getIconImage());
        //SeeFilter filter = new SeeFilter();
    }

//    public Image getIconImage(){
//        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("/es/uvigo/esei/images/icono.png"));
//        return retValue;
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        singIcon = new javax.swing.JLabel();
        universityIcon = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        appName = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        ipFilter = new javax.swing.JButton();
        ipWireshark = new javax.swing.JButton();
        ipInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setAlignmentX(0.0F);
        Header.setAlignmentY(0.0F);
        Header.setMinimumSize(new java.awt.Dimension(860, 38));
        Header.setPreferredSize(new java.awt.Dimension(860, 38));

        singIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uvigo/esei/images/logoSING.png"))); // NOI18N

        universityIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uvigo/esei/images/universidade-vigo.png"))); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(singIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(universityIcon)
                .addGap(54, 54, 54))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(singIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(universityIcon)
                .addContainerGap())
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 862, 80));
        Header.getAccessibleContext().setAccessibleName("");

        Body.setAlignmentX(0.0F);
        Body.setAlignmentY(0.0F);
        Body.setMinimumSize(new java.awt.Dimension(860, 362));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uvigo/esei/images/shark_1.png"))); // NOI18N
        icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        appName.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName.setText("FilterAnalyzer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 862, 365));

        Footer.setMinimumSize(new java.awt.Dimension(0, 0));
        Footer.setPreferredSize(new java.awt.Dimension(852, 39));

        ipFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uvigo/esei/images/embudo.png"))); // NOI18N
        ipFilter.setText("Create Filter");
        ipFilter.setMaximumSize(new java.awt.Dimension(109, 23));
        ipFilter.setMinimumSize(new java.awt.Dimension(109, 23));
        ipFilter.setPreferredSize(new java.awt.Dimension(109, 23));
        ipFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipFilterActionPerformed(evt);
            }
        });

        ipWireshark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uvigo/esei/images/shark.png"))); // NOI18N
        ipWireshark.setText("Open Wireshark");
        ipWireshark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipWiresharkActionPerformed(evt);
            }
        });

        ipInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uvigo/esei/images/informacion.png"))); // NOI18N
        ipInfo.setText("Information");
        ipInfo.setMaximumSize(new java.awt.Dimension(123, 23));
        ipInfo.setMinimumSize(new java.awt.Dimension(123, 23));
        ipInfo.setPreferredSize(new java.awt.Dimension(123, 23));
        ipInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(ipFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipWireshark, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(ipWireshark, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ipFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 445, 860, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Initialize Wireshark together with the FilterAnalyzer.lua plugin.*/
    private void ipWiresharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipWiresharkActionPerformed
        // TODO add your handling code here:
        try {
            String r = java.lang.System.getProperty("user.dir");
            String [] cmd = {"wireshark","-X","lua_script:" + r + "/FilterAnalyzer.lua"};
            Runtime.getRuntime().exec(cmd);
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(this, "Invalid comand.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ipWiresharkActionPerformed

    /*Make the call to SelectTypeFilter, which allows you to select the type of filter to create.*/
    private void ipFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipFilterActionPerformed
        // TODO add your handling code here:
        SelectTypeFilter obj = new SelectTypeFilter();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ipFilterActionPerformed

    /*Report on the different sections available in the main menu.*/
    private void ipInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipInfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "To start select one of the options (Press x to exit):\n" +
"\tOpen Wireshark: Allows you to start Wireshark with the menu in order to load the created filter files, see the results and reset them.\n" +
"\tCreate Filter: Allows the creation of a filter file (udp, tcp, ip or nDpi) according to the allowed parameters.\n", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ipInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel appName;
    private javax.swing.JLabel icon;
    private javax.swing.JButton ipFilter;
    private javax.swing.JButton ipInfo;
    private javax.swing.JButton ipWireshark;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel singIcon;
    private javax.swing.JLabel universityIcon;
    // End of variables declaration//GEN-END:variables
}
