/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.uvigo.esei.filter;


import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class SelectTypeFilter extends javax.swing.JFrame {

    /**
     * Creates new form SelectType
     */
    
    SeeFilter filter;
    
    public SelectTypeFilter() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Select Type Filter");
        //MenuFrame mf = new MenuFrame();
        //this.setIconImage(mf.getIconImage());
        filter = new SeeFilter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Header = new javax.swing.JPanel();
        Body = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UDP_BUTTON = new javax.swing.JButton();
        TCP_BUTTON = new javax.swing.JButton();
        IP_BUTTON = new javax.swing.JButton();
        ICMP_BUTTON = new javax.swing.JButton();
        Footer = new javax.swing.JPanel();
        ipBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setAlignmentX(0.0F);
        Header.setAlignmentY(0.0F);
        Header.setMinimumSize(new java.awt.Dimension(860, 38));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 862, 40));

        Body.setAlignmentX(0.0F);
        Body.setAlignmentY(0.0F);
        Body.setMinimumSize(new java.awt.Dimension(860, 362));
        Body.setPreferredSize(new java.awt.Dimension(860, 362));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT THE FILTER´S TYPE TO CREATE A FILTER.");

        jPanel1.setLayout(new java.awt.GridLayout());

        UDP_BUTTON.setText("UDP PACKET");
        UDP_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UDP_BUTTONActionPerformed(evt);
            }
        });
        jPanel1.add(UDP_BUTTON);

        TCP_BUTTON.setText("TCP PACKET");
        TCP_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCP_BUTTONActionPerformed(evt);
            }
        });
        jPanel1.add(TCP_BUTTON);

        IP_BUTTON.setText("IP PACKET");
        IP_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IP_BUTTONActionPerformed(evt);
            }
        });
        jPanel1.add(IP_BUTTON);

        ICMP_BUTTON.setText("ICMP PACKET ");
        ICMP_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICMP_BUTTONActionPerformed(evt);
            }
        });
        jPanel1.add(ICMP_BUTTON);

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        getContentPane().add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 862, 190));

        Footer.setPreferredSize(new java.awt.Dimension(852, 39));

        ipBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/uvigo/esei/images/back.png"))); // NOI18N
        ipBack.setAlignmentY(0.0F);
        ipBack.setLabel("Back");
        ipBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(768, Short.MAX_VALUE)
                .addComponent(ipBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ipBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 445, 860, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String text = "";
    /*Allows the return to the previous menu.*/
    private void ipBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipBackActionPerformed
        // TODO add your handling code here:
        MenuFrame obj = new MenuFrame();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ipBackActionPerformed

    private void UDP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UDP_BUTTONActionPerformed
        CreateUdpFilter udpF = new CreateUdpFilter();
        udpF.setVisible(true);
        dispose();
    }//GEN-LAST:event_UDP_BUTTONActionPerformed

    private void TCP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCP_BUTTONActionPerformed
        CreateTcpFilter tcpF = new CreateTcpFilter();
        tcpF.setVisible(true);
        dispose();
    }//GEN-LAST:event_TCP_BUTTONActionPerformed

    private void IP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IP_BUTTONActionPerformed
        CreateIpFilter ipF = new CreateIpFilter();
        ipF.setVisible(true);
        dispose();
    }//GEN-LAST:event_IP_BUTTONActionPerformed

    private void ICMP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICMP_BUTTONActionPerformed
        CreateICMPFilter icmpF = new CreateICMPFilter();
        icmpF.setVisible(true);
        dispose();
    }//GEN-LAST:event_ICMP_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectTypeFilter().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JButton ICMP_BUTTON;
    private javax.swing.JButton IP_BUTTON;
    private javax.swing.JButton TCP_BUTTON;
    private javax.swing.JButton UDP_BUTTON;
    private javax.swing.JButton ipBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
